server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/Person
    username: postgres
    password: test
  flyway:
    url: jdbc:postgresql://localhost:5432/Person
    username: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    locations: classpath:db/migration
